export const CANDY_CREATE_REQUEST = "CANDY_CREATE_REQUEST";
export const CANDY_CREATE_SUCCESS = "CANDY_CREATE_SUCCESS";
export const CANDY_CREATE_FAIL = "CANDY_CREATE_FAIL";
export const CANDY_CREATE_RESET = "CANDY_CREATE_RESET";

export const CANDY_LIST_REQUEST = "CANDY_LIST_REQUEST";
export const CANDY_LIST_SUCCESS = "CANDY_LIST_SUCCESS";
export const CANDY_LIST_FAIL = "CANDY_LIST_FAIL";

export const CANDY_EXAMPLE_LIST_REQUEST = "CANDY_EXAMPLE_LIST_REQUEST";
export const CANDY_EXAMPLE_LIST_SUCCESS = "CANDY_EXAMPLE_LIST_SUCCESS";
export const CANDY_EXAMPLE_LIST_FAIL = "CANDY_EXAMPLE_LIST_FAIL";

export const CANDY_DETAILS_REQUEST = "CANDY_DETAILS_REQUEST";
export const CANDY_DETAILS_SUCCESS = "CANDY_DETAILS_SUCCESS";
export const CANDY_DETAILS_FAIL = "CANDY_DETAILS_FAIL";

export const CANDY_UPDATE_REQUEST = "CANDY_UPDATE_REQUEST";
export const CANDY_UPDATE_SUCCESS = "CANDY_UPDATE_SUCCESS";
export const CANDY_UPDATE_FAIL = "CANDY_UPDATE_FAIL";
export const CANDY_UPDATE_RESET = "CANDY_UPDATE_RESET";

export const CANDY_DELETE_REQUEST = "CANDY_DELETE_REQUEST";
export const CANDY_DELETE_SUCCESS = "CANDY_DELETE_SUCCESS";
export const CANDY_DELETE_FAIL = "CANDY_DELETE_FAIL";

export const CANDY_CREATE_REVIEW_REQUEST = "CANDY_CREATE_REVIEW_REQUEST"
export const CANDY_CREATE_REVIEW_SUCCESS = "CANDY_CREATE_REVIEW_SUCCESS"
export const CANDY_CREATE_REVIEW_FAIL = "CANDY_CREATE_REVIEW_FAIL"
export const CANDY_CREATE_REVIEW_RESET = "CANDY_CREATE_REVIEW_RESET"
