export const JELLY_CREATE_REQUEST = "JELLY_CREATE_REQUEST";
export const JELLY_CREATE_SUCCESS = "JELLY_CREATE_SUCCESS";
export const JELLY_CREATE_FAIL = "JELLY_CREATE_FAIL";
export const JELLY_CREATE_RESET = "JELLY_CREATE_RESET";

export const JELLY_LIST_REQUEST = "JELLY_LIST_REQUEST";
export const JELLY_LIST_SUCCESS = "JELLY_LIST_SUCCESS";
export const JELLY_LIST_FAIL = "JELLY_LIST_FAIL";

export const JELLY_DETAILS_REQUEST = "JELLY_DETAILS_REQUEST";
export const JELLY_DETAILS_SUCCESS = "JELLY_DETAILS_SUCCESS";
export const JELLY_DETAILS_FAIL = "JELLY_DETAILS_FAIL";

export const JELLY_UPDATE_REQUEST = "JELLY_UPDATE_REQUEST";
export const JELLY_UPDATE_SUCCESS = "JELLY_UPDATE_SUCCESS";
export const JELLY_UPDATE_FAIL = "JELLY_UPDATE_FAIL";
export const JELLY_UPDATE_RESET = "JELLY_UPDATE_RESET";

export const JELLY_DELETE_REQUEST = "JELLY_DELETE_REQUEST";
export const JELLY_DELETE_SUCCESS = "JELLY_DELETE_SUCCESS";
export const JELLY_DELETE_FAIL = "JELLY_DELETE_FAIL";